### ISSUE TITLE
give a complied file

### ISSUE THREAD

**Issue by DotRacel** [rochus-keller/LjTools#2]
it's a little bit hard for me to set up a environment to compile this, can you just give a download link?

**Comment by rochus-keller** [comment]
There are two apps you can build in this repo, LjAsmEditor.pro and LjBcViewer.pro. Which one are you up to and on which OS/version? Did you have a look at the build steps in the readme file?

**Comment by DotRacel** [comment]
> There are two apps you can build in this repo, LjAsmEditor.pro and LjBcViewer.pro. Which one are you up to and on which OS/version? Did you have a look at the build steps in the readme file?

hmm, it's too complex for me, i need to spend hours doing it. i dont really have much time these days, so im asking for the complied file directly. 

btw does these tool support ".ljbc" file?

**Comment by rochus-keller** [comment]
The AsmEditor is used to create and edit the ljasm files. It generates LuaJIT bytecode files when compiling the ljasm files. The bytecode files usually have a suffix like .bc or .lua or .ljbc; doesn't actually matter since LuaJIT doesn't care about the suffix.
The BcViewer is used to create and edit Lua source code files and see how the bytecode looks when compiled; also this tool generates LuaJIT bytecode files.
